# Generated by Django 5.0.3 on 2024-07-11 13:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("todoapp", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="todoitem",
            old_name="descriptiom",
            new_name="description",
        ),
    ]
